# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AXF', '0003_mainshow_shop'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainshow',
            table='axf_mainshow',
        ),
    ]
